import json
import re
import redis
import RedisCache.cache
import json
import requests
import lz4.frame
import urllib.parse

# date_pattern = r"^\d{4}-(?:0?[1-9]|1[0-2])-(?:0?[1-9]|[1-2][0-9]|3[0-1])$"
# temp = "1999-01-31"
# match = re.search(date_pattern, temp)
# pattern2=r"^\d+|(?:\d{4}-(?:0?[1-9]|1[0-2])-(?:0?[1-9]|[1-2][0-9]|3[0-1]))$"
# temp2 = "222222"
# match2 = re.fullmatch(pattern2, temp2)

user_data = json.dumps({"id": 1, "name": "demo_user"})
path = "user/data"
r = redis.Redis(host='localhost', port=6379, db=0)
# print(RedisCache.cache.set_cache(r, path, user_data))
result = RedisCache.cache.get_cache(r, "hello")
temp_site = "https://www.google.com/path1/path2?search=&index=1" 
parsed_url = urllib.parse.urlparse(temp_site)
print(parsed_url.path + '?' + parsed_url.query)
temp_req = requests.get(temp_site)
# print(type(temp_req.json()))
# print(result.decode())
temp_string = '''{
  "queryCost": 24,
  "latitude": 24.86,
  "longitude": 67.01,
  "resolvedAddress": "karachi",
  "address": "karachi",
  "timezone": "Asia/Karachi",
  "tzoffset": 5.0,
  "days": [
    {
      "datetime": "2025-12-10",
      "datetimeEpoch": 1765306800,
      "tempmax": 87.7,
      "tempmin": 49.9,
      "temp": 67.5,
      "feelslikemax": 84.0,
      "feelslikemin": 49.3,
      "feelslike": 66.6,
      "dew": 36.8,
      "humidity": 38.9,
      "precip": 0.0,
      "precipprob": 0.0,
      "precipcover": 0.0,
      "preciptype": null,
      "snow": 0.0,
      "snowdepth": null,
      "windgust": 12.5,
      "windspeed": 11.4,
      "winddir": 281.2,
      "pressure": 1018.2,
      "cloudcover": 3.3,
      "visibility": 2.4,
      "solarradiation": 178.6,
      "solarenergy": 15.4,
      "uvindex": 7.0,
      "severerisk": 10.0,
      "sunrise": "07:05:59",
      "sunriseEpoch": 1765332359,
      "sunset": "17:43:38",
      "sunsetEpoch": 1765370618,
      "moonphase": 0.68,
      "conditions": "Clear",
      "description": "Clear conditions throughout the day.",
      "icon": "clear-day",
      "stations": [
        "OPKC"
      ],
      "source": "obs",
      "hours": [
        {
          "datetime": "00:00:00",
          "datetimeEpoch": 1765306800,
          "temp": 58.9,
          "feelslike": 58.9,
          "humidity": 54.87,
          "dew": 42.7,
          "precip": 0.0,
          "precipprob": 0.0,
          "snow": 0.0,
          "snowdepth": null,
          "preciptype": null,
          "windgust": 4.7,
          "windspeed": 4.7,
          "winddir": 30.0,
          "pressure": 1018.0,
          "visibility": 1.9,
          "cloudcover": 0.0,
          "solarradiation": 0.0,
          "solarenergy": 0.0,
          "uvindex": 0.0,
          "severerisk": 10.0,
          "conditions": "Clear",
          "icon": "clear-night",
          "stations": [
            "OPKC"
          ],
          "source": "obs"
        },
        {
          "datetime": "01:00:00",
          "datetimeEpoch": 1765310400,
          "temp": 57.1,
          "feelslike": 57.1,
          "humidity": 58.53,
          "dew": 42.7,
          "precip": 0.0,
          "precipprob": 0.0,
          "snow": 0.0,
          "snowdepth": null,
          "preciptype": null,
          "windgust": 5.4,
          "windspeed": 3.4,
          "winddir": 30.0,
          "pressure": 1018.0,
          "visibility": 1.9,
          "cloudcover": 4.6,
          "solarradiation": 0.0,
          "solarenergy": 0.0,
          "uvindex": 0.0,
          "severerisk": 10.0,
          "conditions": "Clear",
          "icon": "clear-night",
          "stations": [
            "OPKC"
          ],
          "source": "obs"
        },
        {
          "datetime": "02:00:00",
          "datetimeEpoch": 1765314000,
          "temp": 57.1,
          "feelslike": 57.1,
          "humidity": 54.61,
          "dew": 40.9,
          "precip": 0.0,
          "precipprob": 0.0,
          "snow": 0.0,
          "snowdepth": null,
          "preciptype": null,
          "windgust": 6.9,
          "windspeed": 3.4,
          "winddir": 360.0,
          "pressure": 1018.0,
          "visibility": 1.9,
          "cloudcover": 5.0,
          "solarradiation": 0.0,
          "solarenergy": 0.0,
          "uvindex": 0.0,
          "severerisk": 10.0,
          "conditions": "Clear",
          "icon": "clear-night",
          "stations": [
            "OPKC"
          ],
          "source": "obs"
        },
        {
          "datetime": "03:00:00",
          "datetimeEpoch": 1765317600,
          "temp": 55.3,
          "feelslike": 55.3,
          "humidity": 54.35,
          "dew": 39.1,
          "precip": 0.0,
          "precipprob": 0.0,
          "snow": 0.0,
          "snowdepth": null,
          "preciptype": null,
          "windgust": 8.5,
          "windspeed": 3.4,
          "winddir": 40.0,
          "pressure": 1018.0,
          "visibility": 1.9,
          "cloudcover": 2.4,
          "solarradiation": 0.0,
          "solarenergy": 0.0,
          "uvindex": 0.0,
          "severerisk": 10.0,
          "conditions": "Clear",
          "icon": "clear-night",
          "stations": [
            "OPKC"
          ],
          "source": "obs"
        },
        {
          "datetime": "04:00:00",
          "datetimeEpoch": 1765321200,
          "temp": 55.3,
          "feelslike": 55.3,
          "humidity": 76.67,
          "dew": 48.1,
          "precip": 0.0,
          "precipprob": 0.0,
          "snow": 0.0,
          "snowdepth": null,
          "preciptype": null,
          "windgust": 9.2,
          "windspeed": 0.0,
          "winddir": 0.0,
          "pressure": 1018.0,
          "visibility": 1.9,
          "cloudcover": 5.0,
          "solarradiation": 0.0,
          "solarenergy": 0.0,
          "uvindex": 0.0,
          "severerisk": 10.0,
          "conditions": "Clear",
          "icon": "clear-night",
          "stations": [
            "OPKC"
          ],
          "source": "obs"
        },
        {
          "datetime": "05:00:00",
          "datetimeEpoch": 1765324800,
          "temp": 53.5,
          "feelslike": 53.5,
          "humidity": 58.04,
          "dew": 39.1,
          "precip": 0.0,
          "precipprob": 0.0,
          "snow": null,
          "snowdepth": null,
          "preciptype": null,
          "windgust": 8.1,
          "windspeed": 4.7,
          "winddir": 50.0,
          "pressure": 1018.0,
          "visibility": 2.5,
          "cloudcover": 5.0,
          "solarradiation": 0.0,
          "solarenergy": 0.0,
          "uvindex": 0.0,
          "severerisk": 10.0,
          "conditions": "Clear",
          "icon": "clear-night",
          "stations": [
            "OPKC"
          ],
          "source": "obs"
        },
        {
          "datetime": "06:00:00",
          "datetimeEpoch": 1765328400,
          "temp": 51.7,
          "feelslike": 51.7,
          "humidity": 62.0,
          "dew": 39.1,
          "precip": 0.0,
          "precipprob": 0.0,
          "snow": 0.0,
          "snowdepth": null,
          "preciptype": null,
          "windgust": 7.2,
          "windspeed": 0.0,
          "winddir": 0.0,
          "pressure": 1018.0,
          "visibility": 2.5,
          "cloudcover": 5.0,
          "solarradiation": 0.0,
          "solarenergy": 0.0,
          "uvindex": 0.0,
          "severerisk": 10.0,
          "conditions": "Clear",
          "icon": "clear-night",
          "stations": [
            "OPKC"
          ],
          "source": "obs"
        },
        {
          "datetime": "07:00:00",
          "datetimeEpoch": 1765332000,
          "temp": 49.9,
          "feelslike": 49.3,
          "humidity": 61.77,
          "dew": 37.3,
          "precip": 0.0,
          "precipprob": 0.0,
          "snow": 0.0,
          "snowdepth": null,
          "preciptype": null,
          "windgust": 5.8,
          "windspeed": 3.4,
          "winddir": 50.0,
          "pressure": 1019.0,
          "visibility": 2.5,
          "cloudcover": 4.9,
          "solarradiation": 0.0,
          "solarenergy": 0.0,
          "uvindex": 0.0,
          "severerisk": 10.0,
          "conditions": "Clear",
          "icon": "clear-night",
          "stations": [
            "OPKC"
          ],
          "source": "obs"
        },
        {
          "datetime": "08:00:00",
          "datetimeEpoch": 1765335600,
          "temp": 51.7,
          "feelslike": 51.7,
          "humidity": 62.0,
          "dew": 39.1,
          "precip": 0.0,
          "precipprob": 0.0,
          "snow": 0.0,
          "snowdepth": null,
          "preciptype": null,
          "windgust": 5.1,
          "windspeed": 5.8,
          "winddir": 50.0,
          "pressure": 1019.0,
          "visibility": 1.9,
          "cloudcover": 5.0,
          "solarradiation": 38.0,
          "solarenergy": 0.1,
          "uvindex": 0.0,
          "severerisk": 10.0,
          "conditions": "Clear",
          "icon": "clear-day",
          "stations": [
            "OPKC"
          ],
          "source": "obs"
        },
        {
          "datetime": "09:00:00",
          "datetimeEpoch": 1765339200,
          "temp": 64.3,
          "feelslike": 64.3,
          "humidity": 34.24,
          "dew": 35.5,
          "precip": 0.0,
          "precipprob": 0.0,
          "snow": 0.0,
          "snowdepth": null,
          "preciptype": null,
          "windgust": 4.5,
          "windspeed": 5.8,
          "winddir": 30.0,
          "pressure": 1020.0,
          "visibility": 1.9,
          "cloudcover": 5.0,
          "solarradiation": 214.0,
          "solarenergy": 0.8,
          "uvindex": 2.0,
          "severerisk": 10.0,
          "conditions": "Clear",
          "icon": "clear-day",
          "stations": [
            "OPKC"
          ],
          "source": "obs"
        },
        {
          "datetime": "10:00:00",
          "datetimeEpoch": 1765342800,
          "temp": 73.3,
          "feelslike": 73.3,
          "humidity": 23.41,
          "dew": 33.7,
          "precip": 0.0,
          "precipprob": 0.0,
          "snow": 0.0,
          "snowdepth": null,
          "preciptype": null,
          "windgust": 2.9,
          "windspeed": 4.7,
          "winddir": 360.0,
          "pressure": 1020.0,
          "visibility": 1.9,
          "cloudcover": 6.3,
          "solarradiation": 406.0,
          "solarenergy": 1.5,
          "uvindex": 4.0,
          "severerisk": 10.0,
          "conditions": "Clear",
          "icon": "clear-day",
          "stations": [
            "OPKC"
          ],
          "source": "obs"
        },
        {
          "datetime": "11:00:00",
          "datetimeEpoch": 1765346400,
          "temp": 80.5,
          "feelslike": 78.8,
          "humidity": 18.44,
          "dew": 33.7,
          "precip": 0.0,
          "precipprob": 0.0,
          "snow": null,
          "snowdepth": null,
          "preciptype": null,
          "windgust": 3.4,
          "windspeed": 3.4,
          "winddir": 330.0,
          "pressure": 1020.0,
          "visibility": 2.5,
          "cloudcover": 6.2,
          "solarradiation": 561.0,
          "solarenergy": 2.0,
          "uvindex": 6.0,
          "severerisk": 10.0,
          "conditions": "Clear",
          "icon": "clear-day",
          "stations": [
            "OPKC"
          ],
          "source": "obs"
        },
        {
          "datetime": "12:00:00",
          "datetimeEpoch": 1765350000,
          "temp": 84.1,
          "feelslike": 81.2,
          "humidity": 14.19,
          "dew": 30.1,
          "precip": 0.0,
          "precipprob": 0.0,
          "snow": 0.0,
          "snowdepth": null,
          "preciptype": null,
          "windgust": 5.4,
          "windspeed": 5.8,
          "winddir": 270.0,
          "pressure": 1019.0,
          "visibility": 2.5,
          "cloudcover": 5.0,
          "solarradiation": 658.0,
          "solarenergy": 2.4,
          "uvindex": 7.0,
          "severerisk": 10.0,
          "conditions": "Clear",
          "icon": "clear-day",
          "stations": [
            "OPKC"
          ],
          "source": "obs"
        },
        {
          "datetime": "13:00:00",
          "datetimeEpoch": 1765353600,
          "temp": 87.7,
          "feelslike": 84.0,
          "humidity": 10.13,
          "dew": 24.7,
          "precip": 0.0,
          "precipprob": 0.0,
          "snow": 0.0,
          "snowdepth": null,
          "preciptype": null,
          "windgust": 8.9,
          "windspeed": 6.9,
          "winddir": 250.0,
          "pressure": 1018.0,
          "visibility": 3.1,
          "cloudcover": 5.0,
          "solarradiation": 686.0,
          "solarenergy": 2.5,
          "uvindex": 7.0,
          "severerisk": 10.0,
          "conditions": "Clear",
          "icon": "clear-day",
          "stations": [
            "OPKC"
          ],
          "source": "obs"
        },
        {
          "datetime": "14:00:00",
          "datetimeEpoch": 1765357200,
          "temp": 87.7,
          "feelslike": 84.0,
          "humidity": 9.4,
          "dew": 22.9,
          "precip": 0.0,
          "precipprob": 0.0,
          "snow": 0.0,
          "snowdepth": null,
          "preciptype": null,
          "windgust": 10.3,
          "windspeed": 6.9,
          "winddir": 230.0,
          "pressure": 1017.0,
          "visibility": 3.1,
          "cloudcover": 5.3,
          "solarradiation": 641.0,
          "solarenergy": 2.3,
          "uvindex": 6.0,
          "severerisk": 10.0,
          "conditions": "Clear",
          "icon": "clear-day",
          "stations": [
            "OPKC"
          ],
          "source": "obs"
        },
        {
          "datetime": "15:00:00",
          "datetimeEpoch": 1765360800,
          "temp": 85.9,
          "feelslike": 82.6,
          "humidity": 12.45,
          "dew": 28.3,
          "precip": 0.0,
          "precipprob": 0.0,
          "snow": 0.0,
          "snowdepth": null,
          "preciptype": null,
          "windgust": 11.0,
          "windspeed": 9.2,
          "winddir": 210.0,
          "pressure": 1017.0,
          "visibility": 3.7,
          "cloudcover": 5.0,
          "solarradiation": 533.0,
          "solarenergy": 1.9,
          "uvindex": 5.0,
          "severerisk": 10.0,
          "conditions": "Clear",
          "icon": "clear-day",
          "stations": [
            "OPKC"
          ],
          "source": "obs"
        },
        {
          "datetime": "16:00:00",
          "datetimeEpoch": 1765364400,
          "temp": 84.1,
          "feelslike": 81.2,
          "humidity": 16.41,
          "dew": 33.7,
          "precip": 0.0,
          "precipprob": 0.0,
          "snow": 0.0,
          "snowdepth": null,
          "preciptype": null,
          "windgust": 12.1,
          "windspeed": 11.4,
          "winddir": 230.0,
          "pressure": 1016.0,
          "visibility": 3.7,
          "cloudcover": 0.2,
          "solarradiation": 372.0,
          "solarenergy": 1.3,
          "uvindex": 4.0,
          "severerisk": 10.0,
          "conditions": "Clear",
          "icon": "clear-day",
          "stations": [
            "OPKC"
          ],
          "source": "obs"
        },
        {
          "datetime": "17:00:00",
          "datetimeEpoch": 1765368000,
          "temp": 82.3,
          "feelslike": 79.9,
          "humidity": 15.04,
          "dew": 30.1,
          "precip": 0.0,
          "precipprob": 0.0,
          "snow": null,
          "snowdepth": null,
          "preciptype": null,
          "windgust": 12.5,
          "windspeed": 11.4,
          "winddir": 240.0,
          "pressure": 1017.0,
          "visibility": 3.7,
          "cloudcover": 5.0,
          "solarradiation": 178.0,
          "solarenergy": 0.6,
          "uvindex": 2.0,
          "severerisk": 10.0,
          "conditions": "Clear",
          "icon": "clear-day",
          "stations": [
            "OPKC"
          ],
          "source": "obs"
        },
        {
          "datetime": "18:00:00",
          "datetimeEpoch": 1765371600,
          "temp": 76.9,
          "feelslike": 76.9,
          "humidity": 22.3,
          "dew": 35.5,
          "precip": 0.0,
          "precipprob": 0.0,
          "snow": 0.0,
          "snowdepth": null,
          "preciptype": null,
          "windgust": 12.5,
          "windspeed": 6.9,
          "winddir": 240.0,
          "pressure": 1017.0,
          "visibility": 2.5,
          "cloudcover": 0.0,
          "solarradiation": 0.0,
          "solarenergy": 0.0,
          "uvindex": 0.0,
          "severerisk": 10.0,
          "conditions": "Clear",
          "icon": "clear-night",
          "stations": [
            "OPKC"
          ],
          "source": "obs"
        },
        {
          "datetime": "19:00:00",
          "datetimeEpoch": 1765375200,
          "temp": 69.7,
          "feelslike": 69.7,
          "humidity": 30.5,
          "dew": 37.3,
          "precip": 0.0,
          "precipprob": 0.0,
          "snow": 0.0,
          "snowdepth": null,
          "preciptype": null,
          "windgust": 11.9,
          "windspeed": 4.7,
          "winddir": 240.0,
          "pressure": 1018.0,
          "visibility": 2.5,
          "cloudcover": 0.0,
          "solarradiation": 0.0,
          "solarenergy": 0.0,
          "uvindex": 0.0,
          "severerisk": 10.0,
          "conditions": "Clear",
          "icon": "clear-night",
          "stations": [
            "OPKC"
          ],
          "source": "obs"
        },
        {
          "datetime": "20:00:00",
          "datetimeEpoch": 1765378800,
          "temp": 67.9,
          "feelslike": 67.9,
          "humidity": 40.02,
          "dew": 42.7,
          "precip": 0.0,
          "precipprob": 0.0,
          "snow": 0.0,
          "snowdepth": null,
          "preciptype": null,
          "windgust": 11.9,
          "windspeed": 3.4,
          "winddir": 210.0,
          "pressure": 1018.0,
          "visibility": 1.9,
          "cloudcover": 0.0,
          "solarradiation": 0.0,
          "solarenergy": 0.0,
          "uvindex": 0.0,
          "severerisk": 10.0,
          "conditions": "Clear",
          "icon": "clear-night",
          "stations": [
            "OPKC"
          ],
          "source": "obs"
        },
        {
          "datetime": "21:00:00",
          "datetimeEpoch": 1765382400,
          "temp": 66.1,
          "feelslike": 66.1,
          "humidity": 42.59,
          "dew": 42.7,
          "precip": 0.0,
          "precipprob": 0.0,
          "snow": 0.0,
          "snowdepth": null,
          "preciptype": null,
          "windgust": 11.0,
          "windspeed": 0.0,
          "winddir": 0.0,
          "pressure": 1018.0,
          "visibility": 1.9,
          "cloudcover": 0.0,
          "solarradiation": 0.0,
          "solarenergy": 0.0,
          "uvindex": 0.0,
          "severerisk": 10.0,
          "conditions": "Clear",
          "icon": "clear-night",
          "stations": [
            "OPKC"
          ],
          "source": "obs"
        },
        {
          "datetime": "22:00:00",
          "datetimeEpoch": 1765386000,
          "temp": 60.7,
          "feelslike": 60.7,
          "humidity": 51.47,
          "dew": 42.7,
          "precip": 0.0,
          "precipprob": 0.0,
          "snow": 0.0,
          "snowdepth": null,
          "preciptype": null,
          "windgust": 9.6,
          "windspeed": 4.7,
          "winddir": 30.0,
          "pressure": 1019.0,
          "visibility": 2.5,
          "cloudcover": 0.0,
          "solarradiation": 0.0,
          "solarenergy": 0.0,
          "uvindex": 0.0,
          "severerisk": 10.0,
          "conditions": "Clear",
          "icon": "clear-night",
          "stations": [
            "OPKC"
          ],
          "source": "obs"
        },
        {
          "datetime": "23:00:00",
          "datetimeEpoch": 1765389600,
          "temp": 58.9,
          "feelslike": 58.9,
          "humidity": 51.19,
          "dew": 40.9,
          "precip": 0.0,
          "precipprob": 0.0,
          "snow": null,
          "snowdepth": null,
          "preciptype": null,
          "windgust": 8.9,
          "windspeed": 4.7,
          "winddir": 40.0,
          "pressure": 1019.0,
          "visibility": 2.5,
          "cloudcover": 0.0,
          "solarradiation": 0.0,
          "solarenergy": 0.0,
          "uvindex": 0.0,
          "severerisk": 10.0,
          "conditions": "Clear",
          "icon": "clear-night",
          "stations": [
            "OPKC"
          ],
          "source": "obs"
        }
      ]
    }
  ],
  "stations": {
    "OPKC": {
      "distance": 12911.0,
      "latitude": 24.9,
      "longitude": 67.13,
      "useCount": 0,
      "id": "OPKC",
      "name": "OPKC",
      "quality": 50,
      "contribution": 0.0
    }
  }
}'''
compressed_string = lz4.frame.compress(temp_string.encode())
original_string = lz4.frame.decompress(compressed_string)
# print(len(temp_string.encode()))
# print(f"original_string: {original_string} Size: {len(original_string)}\nCompressed String: {compressed_string} Size: {len(compressed_string)}")